

print()
print("REQUIRED FOR 80 & 100 POINT VERSIONS")
print()
print("********************************************")
print("LAB 03C, THE FIRST PYTHON PROGRAM IN AN IDE")
print("100 POINT VERSION")
print("BY NILO MACKEY")
print("***********************")
print()
print("A poet I am not")
print("Don't claim to be")
print("But what I wrote")
print("Did come from me")
print()
print("REQUIRED FOR 100 POINT VERSION")
print()
print("+---------------+")
print("| +-+  @ @  +-+ |")
print("| | | ( ^ ) | | |")
print("+-+ +---U---+ +-+")
print()
